import re

VAR_TOKEN_START = "{{"
VAR_TOKEN_END = "}}" 
BLOCK_TOKEN_START = "{%"
BLOCK_TOKEN_END = "%}"

VAR_FRAGMENT = 0
OPEN_BLOCK_FRAGMENT = 1
CLOSE_BLOCK_FRAGMENT = 2
TEXT_FRAGMENT = 4

TOK_REGEX = re.compile(r"(%s.*?%s|%s.*?%s)" % (
    VAR_TOKEN_START,
    VAR_TOKEN_END,
    BLOCK_TOKEN_START,
    BLOCK_TOKEN_END
))

